Nicer global styling.
house-cats/huyan pull request #190
Opened 2023-01-23 08:18 UTC by YanZ777

Install various fonts to try them out and see if the asthetic looks nice. Use some lorem ipsum text to see how the font looks overall. Add global styles along with global variables for styling. Change the colors to use mostly dark background.
Change the header navigation to flex row and be spaced evenly. Also, make the header be centered overall for now. 

## Outstanding questions 
- So which font do we actually want to go with? 
- Are you ok with this styling so far? 

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/6477059/213993291-7fdea860-c668-4996-92ff-a8c4365d2239.png">

2023-01-30 05:15 UTC, huy-vuong commented
I'm considering if we want to do a different colour background for the header bar, or if it makes more sense to have it the same colour but have a border or something... I haven't worked this out fully yet though, they're just ideas.

---

Here's my experiment with colours:

```css
:root {
   /* Made these darker. */
   --primary-black: #121417;
   --secondary-black: #212227;

   /* No change. */
   --accent-green: #72ba34;

   /* Transposed the values so it's more blue than yellow. */
   --content-white: #d5dce3;
}
```

<img width="1437" alt="Screenshot 2023-01-29 at 1 57 52 PM" src="https://user-images.githubusercontent.com/13926659/215357844-fc456520-984e-42ea-b49c-5ae641211476.png">

Thoughts either way?

2023-01-30 08:05 UTC, YanZ777 commented
> I'm considering if we want to do a different colour background for the header bar, or if it makes more sense to have it the same colour but have a border or something... I haven't worked this out fully yet though, they're just ideas.
> 
> Here's my experiment with colours:
> 
> ```css
> :root {
>    /* Made these darker. */
>    --primary-black: #121417;
>    --secondary-black: #212227;
> 
>    /* No change. */
>    --accent-green: #72ba34;
> 
>    /* Transposed the values so it's more blue than yellow. */
>    --content-white: #d5dce3;
> }
> ```
> 
> <img alt="Screenshot 2023-01-29 at 1 57 52 PM" width="1437" src="https://user-images.githubusercontent.com/13926659/215357844-fc456520-984e-42ea-b49c-5ae641211476.png">
> 
> Thoughts either way?

I'm good with the new colors and can start using those. 
I don't think a border would look good and I prefer to have the header be a different color from the body.

2023-02-08 08:50 UTC, huy-vuong requested changes

2023-02-08 08:50 UTC, huy-vuong commented on web/package.json
> +      "@fontsource/playfair-display": "^4.5.12",
**question:** Are we using all four?

2023-02-08 08:50 UTC, huy-vuong commented on web/src/styles/global.css
> +@import '@fontsource/playfair-display';
**question:** Is the intention to use Lexend for header / body and then Playfair Display otherwise?

2023-02-08 08:50 UTC, huy-vuong commented on web/src/components/HeaderNavigation/HeaderNavigation.jsx
> +            name="Travel &amp; Accomodations"
**blocker:** User-facing typos.

```suggestion
            path="/travel-and-accommodations"
            name="Travel &amp; Accommodations"
```

2023-02-13 08:58 UTC, YanZ777 commented on web/package.json
> +      "@fontsource/playfair-display": "^4.5.12",
Probably not, but I actually don't remember which ones we picked.

2023-02-13 08:58 UTC, YanZ777 commented on web/src/styles/global.css
> +@import '@fontsource/playfair-display';
I don't think we decided.

2023-02-16 12:00 UTC, huy-vuong approved these changes
Fonts are still in the air right now, so approving for now so that we can just have them there to experiment with. We can remove the unused ones once we settle on them.

2023-02-17 08:11 UTC, merged