Join RSVP lookup / editor into single RSVP page
house-cats/huyan pull request #201
Opened 2023-02-08 10:47 UTC by huy-vuong

# Issues

- Closes #159.

# Testing

*(Need to add component tests.)*

2023-02-14 07:03 UTC, YanZ777 commented
What's a name I can test with?

2023-02-14 07:26 UTC, YanZ777 reviewed
Initial comment for now, I wasn't able to fully test this, but that might have been me being a derp.

2023-02-14 07:26 UTC, YanZ777 commented on web/src/components/RsvpLookupForm/RsvpLookupForm.jsx
> +            e.response.status === StatusCodes.NOT_FOUND
**suggestion:** You might want to handle things like where there's no status at all, such an empty response.

2023-02-14 11:46 UTC, huy-vuong commented on web/src/components/RsvpLookupForm/RsvpLookupForm.jsx
> +            e.response.status === StatusCodes.NOT_FOUND
Yeah, that's fair. We shouldn't get empty data, but I guess if we did, I'd probably funnel it to the same `else` case as here with the `'Something is sad right now. Can you let us know?'` message.

2023-02-20 01:36 UTC, YanZ777 requested changes
I'd like a test for the transition between the lookup form and the editor form.

2023-02-20 01:36 UTC, YanZ777 commented on web/src/pages/RsvpPage.test.jsx
> +   });
**suggestion:** Could you add a test to make sure the transition between the components works?

2023-02-20 01:39 UTC, huy-vuong commented on web/src/pages/RsvpPage.test.jsx
> +   });
Oops, this should've been that the editor is in the document and the look is not. Copy-pasting code ftl. ;_;

2023-02-20 01:53 UTC, huy-vuong commented on web/src/pages/RsvpPage.test.jsx
> +   });
*(Discussed in-person. Test is there (see other comment), but it's named badly and I also wrote the wrong `expect`s for it. Oops.)*

2023-02-20 01:57 UTC, YanZ777 approved these changes

2023-02-20 03:34 UTC, merged