Make the website look nice for mobile view.
house-cats/huyan pull request #243
Opened 2023-03-20 05:58 UTC by YanZ777

Add a media query that is all in a hook  so that the correct CSS gets switched to when in mobile view. Add some mocks for the tests that have the media query since they were failing on window.matchMedia

Screenshoot is of Pixel 5 view.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/6477059/226259079-3b853278-a380-49af-99fa-3ca14b5fd4d4.png">

2023-03-20 10:00 UTC, huy-vuong requested changes

2023-03-20 10:00 UTC, huy-vuong commented on web/src/components/HeaderNavigation/HeaderNavigation.jsx
> +         <div className={styles.headerNavigationMobile}>
**blocker:** It looks to me like the only difference is the `styles.headerNavigationMobile` vs. `styles.headerNavigation`. Could we have a ternary expression in `className` instead, so that we avoid repeating the contents of the `<div>`?

```suggestion
         <div className={isMobileView ? styles.headerNavigationMobile : styles.headerNavigation}>
```

2023-03-20 10:00 UTC, huy-vuong commented on web/src/components/HeaderNavigation/HeaderNavigation.css
> +}
**blocker:** Should we have some top-level styling that applies to both `.headerNavigation` and `.headerNavigationMobile` that both versions use? That way we can reduce duplication between these two styles: `display`, `font-family`, `justify-content`, and `position` are the same for instance.

2023-03-20 10:00 UTC, huy-vuong commented on web/src/components/HeaderNavigation/HeaderNavigation.css
> +.headerNavigationMobile {
**question:** Is there a reason we don't use `@media` like we did for `BodyContainer.css`? Like...

```suggestion
@media screen and (max-width: 400px) {
  .headerNavigationMobile {
```

2023-03-21 05:40 UTC, YanZ777 commented on web/src/components/HeaderNavigation/HeaderNavigation.css
> +.headerNavigationMobile {
Actually, you're right. I would just use @media in the css file. I was originally having hooks because I thought there was some logic I would need to implement for mobile only, but I took that out and simplified it a lot, so I don't need the hooks in the first place even.

2023-03-21 05:41 UTC, YanZ777 commented on web/src/hooks/hooks.js
> +      return () => media.removeListener(listener);
This hook is going to get destroyed for now. However, yea, we should use the replacement methods.

2023-03-21 05:42 UTC, YanZ777 commented on web/src/components/Header/Header.jsx
> +   const isMobileView = useMediaQuery('(max-width: 400px)');
Not anymore since mediaQuery is getting removed!

2023-03-21 05:43 UTC, YanZ777 commented on web/src/components/HeaderNavigation/HeaderNavigation.jsx
> +         <div className={styles.headerNavigationMobile}>
Yes, that would make more sense.

2023-03-21 05:50 UTC, YanZ777 commented on web/src/components/HeaderNavigation/HeaderNavigation.css
> +}
If we had sass set up, this would address the code duplication. I haven't set up sass before though and didn't want to do it in this ticket. 
https://sass-lang.com/documentation/at-rules/css
Specifically, if you look at the example with `.print-only`.
Unfortunately, as it is, there's going to be some code duplication.

2023-03-21 09:03 UTC, huy-vuong commented on web/src/components/HeaderNavigation/HeaderNavigation.css
> +}
Would it be doable to do something like this? Or is it a bad idea since it's possible to accidentally forget the 'common' style (`.headerNavigation` in this example)?

```css
/* Common to all form factors. */
.headerNavigation {
   display: flex;
   font-family: 'Playfair Display';
   justify-content: space-evenly;
}

/* Phones. */
.headerNavigationSmall {
   flex-direction: column;
}

/* Tablets, desktops. */
.headerNavigationLarge {
   flex-direction: row;
   top: 30%;
}
```

2023-03-21 09:04 UTC, huy-vuong approved these changes
Code looks good; responded to one of the earlier comments since I had further questions, but feel free to merge this in the meantime.

2023-03-22 03:57 UTC, YanZ777 commented on web/src/components/HeaderNavigation/HeaderNavigation.css
> +}
I'm actually not sure if that would work or not. I suspect it might not because you'd have to have in the code
```
<div className={headerNavigation headerNavigationSmall}/>
```

And in the css file you'd have 
```
.headerNavigation.headerNavigationSmall {
...
}
```

I think that would look kind of complicated and I think just using the @media query to override the specific style we want is cleaner.

2023-03-22 03:57 UTC, merged