Create a new page to hold the rsvp portal form
house-cats/huyan pull request #95
Opened 2022-10-04 06:40 UTC by YanZ777

Rename the tests so that it matches rsvp instead of RSVP.
Change the route names so that one route maps to the form and the other route maps to the portal.
Add a test link to the homepage.

2022-12-27 07:17 UTC, huy-vuong requested changes

2022-12-27 07:17 UTC, huy-vuong commented on web/src/components/RsvpForm/RsvpForm.jsx
> +   const onSubmit = () => {};
**question:** If I ended up moving this function out to a helper function that's defined separately, like:

```
export function submitRsvp() {
   // ...
}
```

...how would you feel?

2022-12-27 07:17 UTC, huy-vuong commented on web/src/components/RsvpForm/RsvpForm.jsx
> +                  <Field type="radio" name="notAttending" value="NOT_GOING" />
**issue:** We'll want `name` to match to declare these `<Field>`s as part of the same group of radio buttons.

```suggestion
<Field type="radio" name="attending" value="NOT_GOING" />
```

2022-12-27 07:17 UTC, huy-vuong commented on web/src/components/RsvpPortalForm/RsvpPortalForm.jsx
> +               <Field type="lastName" aria-label="last name" name="lastName" />
**question:** Is this a valid value for `Field.type`? I was under the impression that it had to be one of the [supported values for `type` in `<input>`](https://www.w3schools.com/html/html_form_input_types.asp).

2022-12-28 06:12 UTC, YanZ777 commented on web/src/index.jsx
> +               <Route path="/rsvpTest" element={<Rsvp />} />
Yea, I'm ok with these renames.

Did your question get answered earlier? I think we agreed on making an RSVP wrapper of sorts to handle state management.

2022-12-28 06:13 UTC, YanZ777 commented on web/src/components/RsvpForm/RsvpForm.jsx
> +   const onSubmit = () => {};
That's fine if you can. Here I decided not to define it within the props itself since it's not good practice to define functions inside of props.

2022-12-28 06:17 UTC, YanZ777 commented on web/src/components/RsvpPortalForm/RsvpPortalForm.jsx
> +               <Field type="lastName" aria-label="last name" name="lastName" />
Oops, yes you're right.

2022-12-28 11:44 UTC, huy-vuong approved these changes

2022-12-28 11:44 UTC, huy-vuong commented on web/src/pages/RsvpLookup.test.jsx
> +test('renders RsvpLookup page', () => {
**suggestion:** To keep consistent with the phrasing in `RsvpEditor.test.jsx`:

```suggestion
test('renders RSVP lookup page', () => {
```

2022-12-28 11:44 UTC, huy-vuong commented on web/src/pages/RsvpEditor.jsx
> +         <RsvpEditorForm />
**suggestion:** To keep consistent with `RsvpLookup.jsx`, let's change the text from "RSVP" to "RSVP Editor".

2022-12-28 11:44 UTC, huy-vuong commented on web/src/pages/RsvpEditor.test.jsx
> +   memoryRender(<RsvpEditor />);
**suggestion:** To keep consistent with the phrasing in `RsvpLookuptest.jsx`:

```suggestion
test('renders RsvpEditor page', () => {
```

2022-12-29 05:47 UTC, merged